name: Build and SonarCloud Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: ./.github/actions/build-action.yml

      - name: Test
        uses: ./.github/actions/test-action.yml

      - name: SonarCloud Scan
        uses: ./.github/actions/sonarcloud-scan-action.yml

